# Generated by Django 3.0.5 on 2022-08-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20220731_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='num_order',
            field=models.BigIntegerField(null=True),
        ),
    ]
