# Generated by Django 3.0.5 on 2022-08-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_orders_cant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('send', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('num_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Orders')),
            ],
        ),
    ]
