# Generated by Django 3.0.5 on 2022-08-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20220806_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_list',
            name='num_order',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
