# Generated by Django 3.0.5 on 2022-08-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20220806_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pay', models.CharField(max_length=500, null=True)),
                ('num_order', models.CharField(max_length=500, null=True)),
                ('type_pay', models.CharField(max_length=500, null=True)),
                ('total_pay', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
