# Generated by Django 3.0.5 on 2022-08-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Py Confirmed', 'Pay Confirmed')], max_length=50, null=True),
        ),
    ]
