# Generated by Django 3.0.5 on 2022-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='type_pay',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal')], max_length=50, null=True),
        ),
    ]
