# Generated by Django 3.0.5 on 2022-08-15 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20220814_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('num_order', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('send', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.BigIntegerField(null=True)),
                ('num_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Orden')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product')),
            ],
        ),
    ]
