# Generated by Django 3.0.5 on 2022-08-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_orden_orden_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
