# Generated by Django 3.0.5 on 2022-08-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_orden_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='state',
            field=models.CharField(choices=[('Azuay', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
