# Generated by Django 3.0.5 on 2022-08-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_orden_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('description', models.CharField(max_length=100)),
                ('num_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Orden')),
            ],
        ),
    ]
