# Generated by Django 3.0.5 on 2022-08-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_detail_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BigIntegerField(null=True),
        ),
    ]
