# Generated by Django 3.0.5 on 2022-09-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
