# Generated by Django 3.0.5 on 2022-09-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_events_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='deposit_imag',
            field=models.ImageField(blank=True, null=True, upload_to='deposits_image/'),
        ),
        migrations.AddField(
            model_name='pay',
            name='num_depos',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
